-- MySQL Script generated by MySQL Workbench
-- Mon Jun 14 18:17:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grenier
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grenier
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grenier` DEFAULT CHARACTER SET utf8 ;
USE `grenier` ;

-- -----------------------------------------------------
-- Table `grenier`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grenier`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(205) NULL,
  `nom` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL COMMENT 'Mot de passe du compte client\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grenier`.`transporteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grenier`.`transporteur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricule` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL COMMENT 'Mot de passe du compte transporteur',
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_transporteur_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_transporteur_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `grenier`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grenier`.`offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grenier`.`offre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `depart` VARCHAR(45) NULL,
  `arrive` VARCHAR(45) NULL,
  `montant` VARCHAR(45) NULL,
  `placedispo` VARCHAR(45) NULL COMMENT 'Nombre de places disponibles',
  `transporteur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `transporteur_id`),
  INDEX `fk_offre_transporteur_idx` (`transporteur_id` ASC) VISIBLE,
  CONSTRAINT `fk_offre_transporteur`
    FOREIGN KEY (`transporteur_id`)
    REFERENCES `grenier`.`transporteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grenier`.`offre_has_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grenier`.`offre_has_client` (
  `offre_id` INT NOT NULL,
  `offre_transporteur_id` INT NOT NULL,
  `qte` VARCHAR(45) NULL COMMENT 'Le nombre de place ',
  `date` VARCHAR(45) NULL,
  `numComd` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`offre_id`, `offre_transporteur_id`, `user_id`),
  INDEX `fk_offre_has_client_offre1_idx` (`offre_id` ASC, `offre_transporteur_id` ASC) VISIBLE,
  INDEX `fk_offre_has_client_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_offre_has_client_offre1`
    FOREIGN KEY (`offre_id` , `offre_transporteur_id`)
    REFERENCES `grenier`.`offre` (`id` , `transporteur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offre_has_client_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `grenier`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grenier`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grenier`.`paiement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numpaiement` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grenier`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grenier`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
